'\" t
.\"     Title: xfce4-terminal
.\"    Author: Nick Schermer <nick@xfce.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 12/26/2013
.\"    Manual: Xfce
.\"    Source: xfce4-terminal 0.6.3
.\"  Language: English
.\"
.TH "XFCE4\-TERMINAL" "1" "12/26/2013" "xfce4-terminal 0\&.6\&.3" "Xfce"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xfce4-terminal \- Емулятор терміналу для Xfce
.SH "Синопсис"
.HP \w'\fBxfce4\-terminal\fR\ 'u
\fBxfce4\-terminal\fR [ОПЦІЇ...]
.SH "Опис"
.PP
xfce4\-terminal всі знають як емулятор терміналу для X, часто також говорять просто "термінал" або "шелл"\&. Він такий самий як старомодний текстовий інтерфейс, але також може ділити екран з будь\-якою графічною програмою\&. Користувачі WIndows можуть бути вже знайомі з командною стрічкою MS\-DOS, яка має аналогічні функції, пропонуючи командну стрічку DOS для Windows, однак потрібно зазначити, що інтерфейс командної стрічки UNIX пропонує набагато більші можливості і простоту використання, ніж DOS\&."
.PP
xfce4\-terminal емулює програму
xterm, розроблену через X Consortium\&. В свою чергу
xterm
емулює термінал DEC VT102 і також підтримує escape\-комбінації клавіш терміналу DEC VT220\&. Escape\-комбінації клавіш \- це послідовність символів, що починаються з символа
Esc\&. xfce4\-terminal розуміє всі комбінації, які використовуються терміналами VT102 та VT220 для таких функцій, як позиціювання курсора і очищення екрану\&.
.SH "Опції"
.SS "Коротко про опції"
.PP
Тут є опис всіх опцій, погрупованих по типу\&. Пояснення містяться в наступному розділі\&.
.PP
Загальні опції
.RS 4
\fB\-h\fR, \fB\-\-help\fR;
\fB\-V\fR, \fB\-\-version\fR;
\fB\-\-disable\-server\fR;
\fB\-\-default\-display=\fR\fB\fIдисплей\fR\fR;
\fB\-\-default\-working\-directory=\fR\fB\fIтека\fR\fR
.RE
.PP
Вікно або роздільники вкладок
.RS 4
\fB\-\-tab\fR;
\fB\-\-window\fR
.RE
.PP
Опції вкладки
.RS 4
\fB\-x\fR, \fB\-\-execute\fR;
\fB\-e\fR, \fB\-\-command=\fR\fB\fIкоманда\fR\fR;
\fB\-\-working\-directory=\fR\fB\fIтека\fR\fR;
\fB\-T\fR, \fB\-\-title=\fR\fB\fIназва\fR\fR;
\fB\-H\fR, \fB\-\-hold\fR
.RE
.PP
Опції вікна
.RS 4
\fB\-\-display=\fR\fB\fIдисплей\fR\fR;
\fB\-\-drop\-down\fR;
\fB\-\-geometry=\fR\fB\fIгеометрія\fR\fR;
\fB\-\-role=\fR\fB\fIроль\fR\fR;
\fB\-\-startup\-id=\fR\fB\fIстрічка\fR\fR;
\fB\-I, \-\-icon=\fR\fB\fIіконка\fR\fR;
\fB\-\-fullscreen\fR;
\fB\-\-maximize\fR;
\fB\-\-show\-menubar\fR,
\fB\-\-hide\-menubar\fR;
\fB\-\-show\-borders\fR,
\fB\-\-hide\-borders\fR;
\fB\-\-show\-toolbar\fR,
\fB\-\-hide\-toolbar\fR
.RE
.SS "Загальні опції"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Список різних опцій командної стрічки, що підтримуються xfce4\-terminal і вийти
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Показати інформацію про версію і вийти
.RE
.PP
\fB\-\-disable\-server\fR
.RS 4
Не реєструвати з D\-BUS сесією
.RE
.PP
\fB\-\-color\-table\fR
.RS 4
Показує коди кольорів
.RE
.PP
\fB\-\-default\-display=\fR\fB\fIдисплей\fR\fR
.RS 4
Типовий дисплей X для використання\&.
.RE
.PP
\fB\-\-default\-working\-directory=\fR\fB\fIтека\fR\fR
.RS 4
Встановити параметр
\fIdirectory\fR
як типову робочу теку для терміналу
.RE
.SS "Вікно або роздільники вкладок"
.PP
\fB\-\-tab\fR
.RS 4
Відкрити нову вкладку в останньо визначеному вікні; можна вказати більше ніж одну з цих опцій\&.
.sp
Якщо викорстати це як перший параметр, без розділювачів \-\-window, тоді останнє вікно буде ще раз використане\&.
.RE
.PP
\fB\-\-window\fR
.RS 4
Відкрити нове вікно що містить одну вкладку; можна вказати більше ніж одну з цих опцій\&.
.RE
.SS "Опції вкладки"
.PP
\fB\-x\fR, \fB\-\-execute\fR
.RS 4
Запустити нагадування командної стрічки всередині терміналу
.RE
.PP
\fB\-e\fR, \fB\-\-command=\fR\fB\fIкоманда\fR\fR
.RS 4
Запустити
\fIкоманду\fR
всередині терміналу
.RE
.PP
\fB\-\-working\-directory=\fR\fB\fIтека\fR\fR
.RS 4
Встановити параметр
\fIdirectory\fR
як робочу теку для терміналу
.RE
.PP
\fB\-T\fR, \fB\-\-title=\fR\fB\fIназва\fR\fR
.RS 4
Встановлення
\fItitle\fR
як початкової назви вікна терміналу
.RE
.PP
\fB\-H\fR, \fB\-\-hold\fR
.RS 4
Не закривати вікно терміналу після закінчення дочірнього процесу
.RE
.SS "Опції вікна"
.PP
\fB\-\-display=\fR\fB\fIдисплей\fR\fR
.RS 4
Дисплей X для використання з останньо вказаним вікном\&.
.RE
.PP
\fB\-\-drop\-down\fR
.RS 4
Will start the window in drop\-down mode (also called a Quake\-style terminal)\&. This will only apply to the first window started with this option\&. It is advised to bind this to a shortcut in the keyboard preferences\&.
.RE
.PP
\fB\-\-geometry=\fR\fB\fIгеометрія\fR\fR
.RS 4
Налаштувати розміри останнього вказаного вікна до
\fIгеометрії\fR\&. Прочитайте
\fBX\fR(7)
для отримання більше інформації, як вказувати розміри вікон\&.
.RE
.PP
\fB\-\-role=\fR\fB\fIроль\fR\fR
.RS 4
Задати роль останнього вказаного вікна\&. Застосовується тільки до одного вікна і може бути вказано відразу для кожного вікна, яке Ви створюєте з командної стрічки\&. В основному використовується для управління сесіями xfce4\-terminal
.RE
.PP
\fB\-\-startup\-id=\fR\fB\fIстрічка\fR\fR
.RS 4
Показує ідентифікатор запуску востаннє вказаного вікна\&. Використовується для передачі ідентифікатора запуску для сервісу D\-BUS\&.
.RE
.PP
\fB\-I, \-\-icon=\fR\fB\fIіконка\fR\fR
.RS 4
Встановити іконку терміналу як назву іконки або файлу
.RE
.PP
\fB\-\-fullscreen\fR
.RS 4
Встановлює повноекранний режим для востаннє вказаного вікна; застосовується тільки до одного вікна; можна застосувати воднораз для кожного вікна, яке Ви створюєте з командного рядка\&.
.RE
.PP
\fB\-\-maximize\fR
.RS 4
Встановлює максимізований режим для востаннє вказаного вікна; застосовується тільки до одного вікна; можна вказати воднораз для кожного вікна, яке Ви створюєте з командного рядка\&.
.RE
.PP
\fB\-\-show\-menubar\fR
.RS 4
Включає панель меню для востаннє вказаного вікна\&. Можна вказати воднораз для кожного вікна, яке Ви створюєте з командного рядка\&.
.RE
.PP
\fB\-\-hide\-menubar\fR
.RS 4
Виключає панель для востаннє вказаного вікна\&. Можна вказати відразу для кожного вікна, яке Ви створите з командної стрічки\&.
.RE
.PP
\fB\-\-show\-borders\fR
.RS 4
Включає обрамлення вікна для востаннє вказаного вікна\&. Застосовується тільки до одного вікна\&. Можна вказати воднораз для кожного вікна, яке Ви створюєте з командного рядка\&.
.RE
.PP
\fB\-\-hide\-borders\fR
.RS 4
Виключає обрамлення вікна для востаннє вказаного вікна\&. Застосовується тільки до одного вікна\&. Можна вказати воднораз для кожного вікна, яке Ви створюєте з командного рядка\&.
.RE
.PP
\fB\-\-show\-toolbar\fR
.RS 4
Turn on the toolbar for the last\-specified window\&. Applies to only one window\&. Can be specified once for each window you create from the command line\&.
.RE
.PP
\fB\-\-hide\-toolbar\fR
.RS 4
Turn off the toolbar for the last\-specified window\&. Applies to only one window\&. Can be specified once for each window you create from the command line\&.
.RE
.SH "Приклади"
.PP
xfce4\-terminal \-\-geometry 80x40 \-\-command mutt \-\-tab \-\-command mc
.RS 4
Відкриває нове вікно терміналу з розміром 80 колонок і 40 рядками і двома вкладками в ньому, де в першій вкладці запускається команда
\fBmutt\fR, а в другій команда
\fBmc\fR\&.
.RE
.SH "Середовище"
.PP
xfce4\-terminal uses the Basedir Specification as defined on
\m[blue]\fBFreedesktop\&.org\fR\m[]\&\s-2\u[1]\d\s+2
to locate its data and configuration files\&. This means that file locations will be specified as a path relative to the directories described in the specification\&.
.PP
\fI${XDG_CONFIG_HOME}\fR
.RS 4
перша базова тека для пошуку конфігураційних файлів\&. Типово встановлено
~/\&.config/\&.
.RE
.PP
\fI${XDG_CONFIG_DIRS}\fR
.RS 4
Двокрапка розділяє список базових тек, що містять дані конфігурації\&. По замовчуванню програма спочатку шукає в
${sysconfdir}/xdg/\&. Значення
\fI${sysconfdir}\fR
залежить від того способу створення програми і часто може бути
/etc/
для бінарних пакунків\&.
.RE
.PP
\fI${XDG_DATA_HOME}\fR
.RS 4
Коренева тека для всіх специфічних файлів користувача\&. Типово встановлено
~/\&.local/share/\&.
.RE
.PP
\fI${XDG_DATA_DIRS}\fR
.RS 4
Список тек з налаштуваннями, відносно яких будуть шукатися файли даних на додаток до базової теки
\fI${XDG_DATA_HOME}\fR\&. Теки в списку повинні бути відділені двокрапкою\&.
.RE
.SH "Файли"
.PP
${XDG_CONFIG_DIRS}/xfce4/terminal/terminalrc
.RS 4
Це є місце знаходження файлу конфігурації, що містить налаштування, які контролюють вигляд програми xfce4\-terminal\&.
.RE
.SH "Гляньте також"
.PP
\fBbash\fR(1),
\fBX\fR(7)
.SH "AUTHORS"
.PP
\fBNick Schermer\fR <\&nick@xfce\&.org\&>
.RS 4
Розробник
.RE
.PP
\fBBenedikt Meurer\fR <\&benny@xfce\&.org\&>
.br
Розробник програми, ос\-циляції, Розробка системи, 
.RS 4
Розробник
.RE
.SH "NOTES"
.IP " 1." 4
Freedesktop.org
.RS 4
\%http://freedesktop.org/
.RE
