'\" t
.\"     Title: xfce4-terminal
.\"    Author: Nick Schermer <nick@xfce.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 12/26/2013
.\"    Manual: Xfce
.\"    Source: xfce4-terminal 0.6.3
.\"  Language: English
.\"
.TH "XFCE4\-TERMINAL" "1" "12/26/2013" "xfce4-terminal 0\&.6\&.3" "Xfce"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xfce4-terminal \- Um emulador de Terminal para o X
.SH "SINAPSE"
.HP \w'\fBxfce4\-terminal\fR\ 'u
\fBxfce4\-terminal\fR [OPÇÃO...]
.SH "DESCRIçãO"
.PP
xfce4\-terminal é aquilo que é conhecido como um emulador de terminal para o X, vulgarmente referido como terminal ou shell\&. Oferece o equivalente ao antigo ecrã de texto no seu ambiente de trabalho, mas pode facilmente partilhar o ecrã com outras aplicações gráficas\&. Utilizadores Windows podem já estar familarizados com a linha de comandos MS\-DOS, que tem a função de oferecer uma linha de comandos em Windows, contudo a interface em linha de comandos UNIX oferece de longe mais poder e facilidade de uso do que o DOS\&.
.PP
xfce4\-terminal emula a aplicação
xterm
desenvolvida pelo Consórcio X\&. Por outro lado, a aplicação
xterm
emula o terminal DEC VT102 e também suporta as sequências de escape do DEC VT220\&. Uma sequência de escape é uma série de carateres que iniciam com o caráter
Esc\&. xfce4\-terminal aceita todas as sequências que os terminais VT102 e VT220 usam para funções como a colocação do cursor e limpeza do ecrã\&.
.SH "OPçõES"
.SS "Resumo de Opções"
.PP
Aqui está um resumo de todas as opções, agrupadas por tipo\&. As explicações estão nas secções seguintes\&.
.PP
Opções Gerais
.RS 4
\fB\-h\fR, \fB\-\-help\fR;
\fB\-V\fR, \fB\-\-version\fR;
\fB\-\-disable\-server\fR;
\fB\-\-default\-display=\fR\fB\fIecrã\fR\fR;
\fB\-\-default\-working\-directory=\fR\fB\fIdiretório\fR\fR
.RE
.PP
Janela ou Separador
.RS 4
\fB\-\-tab\fR;
\fB\-\-window\fR
.RE
.PP
Opções de Separadores
.RS 4
\fB\-x\fR, \fB\-\-execute\fR;
\fB\-e\fR, \fB\-\-command=\fR\fB\fIcomando\fR\fR;
\fB\-\-working\-directory=\fR\fB\fIdiretório\fR\fR;
\fB\-T\fR, \fB\-\-title=\fR\fB\fItítulo\fR\fR;
\fB\-H\fR, \fB\-\-hold\fR
.RE
.PP
Opções de Janelas
.RS 4
\fB\-\-display=\fR\fB\fIecrã\fR\fR;
\fB\-\-drop\-down\fR;
\fB\-\-geometry=\fR\fB\fIgeometria\fR\fR;
\fB\-\-role=\fR\fB\fIregra\fR\fR;
\fB\-\-startup\-id=\fR\fB\fItexto\fR\fR;
\fB\-I, \-\-icon=\fR\fB\fIícone\fR\fR;
\fB\-\-fullscreen\fR;
\fB\-\-maximize\fR;
\fB\-\-show\-menubar\fR,
\fB\-\-hide\-menubar\fR;
\fB\-\-show\-borders\fR,
\fB\-\-hide\-borders\fR;
\fB\-\-show\-toolbar\fR,
\fB\-\-hide\-toolbar\fR
.RE
.SS "Opções Gerais"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Lista as diferentes opções de linha de comandos suportadas pelo xfce4\-terminal e sai
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Mostra a informação de versão e sai
.RE
.PP
\fB\-\-disable\-server\fR
.RS 4
Não registar com o bus de mensagem de sessão D\-BUS
.RE
.PP
\fB\-\-color\-table\fR
.RS 4
Devolve os códigos de cores
.RE
.PP
\fB\-\-default\-display=\fR\fB\fIecrã\fR\fR
.RS 4
Ecrã X a usar por omissão\&.
.RE
.PP
\fB\-\-default\-working\-directory=\fR\fB\fIdiretório\fR\fR
.RS 4
Definir
\fIdiretório\fR
como diretório de trabalho por omissão para o terminal
.RE
.SS "Janela ou Separador"
.PP
\fB\-\-tab\fR
.RS 4
Abrir um novo separador na última janela especificada; mais que uma destas opções pode ser fornecida\&.
.sp
Se utilizar esta opção, sem os separadores \-\-window, a última janela será reutilizada\&.
.RE
.PP
\fB\-\-window\fR
.RS 4
Abrir uma nova janela contendo um separador; mais que uma destas opções pode ser indicada\&.
.RE
.SS "Opções de Separadores"
.PP
\fB\-x\fR, \fB\-\-execute\fR
.RS 4
Executa o resto da linha de comandos dentro do terminal
.RE
.PP
\fB\-e\fR, \fB\-\-command=\fR\fB\fIcomando\fR\fR
.RS 4
Executar
\fIcomando\fR
dentro do terminal
.RE
.PP
\fB\-\-working\-directory=\fR\fB\fIdiretório\fR\fR
.RS 4
Definir
\fIdirectório\fR
como o diretório de trabalho para o terminal
.RE
.PP
\fB\-T\fR, \fB\-\-title=\fR\fB\fItítulo\fR\fR
.RS 4
Definir
\fItítulo\fR
como título inicial da janela de terminal
.RE
.PP
\fB\-H\fR, \fB\-\-hold\fR
.RS 4
Manter o terminal ativo depois do comando filho terminar
.RE
.SS "Opções de Janelas"
.PP
\fB\-\-display=\fR\fB\fIecrã\fR\fR
.RS 4
Ecrã X a usar na última janela especificada
.RE
.PP
\fB\-\-drop\-down\fR
.RS 4
Will start the window in drop\-down mode (also called a Quake\-style terminal)\&. This will only apply to the first window started with this option\&. It is advised to bind this to a shortcut in the keyboard preferences\&.
.RE
.PP
\fB\-\-geometry=\fR\fB\fIgeometria\fR\fR
.RS 4
Define a geometria da última janela especificada a
\fIgeometria\fR\&. Leia
\fBX\fR(7)
para mais informações sobre a especificação da geometria das janelas\&.
.RE
.PP
\fB\-\-role=\fR\fB\fIregra\fR\fR
.RS 4
Define a regra da última janela especificada para
\fIregra\fR\&. Aplica\-se apenas a uma janela e pode ser especificada uma vez para cada janela que criar na linha de comandos\&. Usado principalmente para a gestão da sessão dentro do xfce4\-terminal\&.
.RE
.PP
\fB\-\-startup\-id=\fR\fB\fItexto\fR\fR
.RS 4
Define o id de notificação de inicialização para a última janela especificada\&. Usada internamente para seguir o mesmo id ao usar o serviço D\-BUS\&.
.RE
.PP
\fB\-I, \-\-icon=\fR\fB\fIícone\fR\fR
.RS 4
Definir o ícone do terminal como um ícone ou o nome do ficheiro\&.
.RE
.PP
\fB\-\-fullscreen\fR
.RS 4
Define a última janela especificada para o modo ecrã inteiro; aplica\-se apenas para uma janela; pode ser especificado uma vez para cada janela criada na linha de comandos\&.
.RE
.PP
\fB\-\-maximize\fR
.RS 4
Coloca a última janela especificada no modo maximizado; aplica\-se apenas a uma janela; pode ser especificado uma vez para cada janela criada na linha de comandos\&.
.RE
.PP
\fB\-\-show\-menubar\fR
.RS 4
Liga a barra de menu para a última janela especificada\&. Pode ser especificado uma vez para cada janela criada na linha de comandos\&.
.RE
.PP
\fB\-\-hide\-menubar\fR
.RS 4
Desliga a barra de menu para a última janela especificada\&. Pode ser especificado uma vez para cada janela criada na linha de comandos\&.
.RE
.PP
\fB\-\-show\-borders\fR
.RS 4
Liga as decorações das janelas para a última janela especificada\&. Aplica\-se apenas a uma janela\&. Pode ser especificado uma vez para cada janela criada na linha de comandos\&.
.RE
.PP
\fB\-\-hide\-borders\fR
.RS 4
Desliga as decorações de janelas para a última janela especificada\&. Aplica\-se apenas a uma janela\&. Pode ser especificado uma vez para cada janela criada na linha de comandos\&.
.RE
.PP
\fB\-\-show\-toolbar\fR
.RS 4
Turn on the toolbar for the last\-specified window\&. Applies to only one window\&. Can be specified once for each window you create from the command line\&.
.RE
.PP
\fB\-\-hide\-toolbar\fR
.RS 4
Turn off the toolbar for the last\-specified window\&. Applies to only one window\&. Can be specified once for each window you create from the command line\&.
.RE
.SH "EXEMPLOS"
.PP
xfce4\-terminal \-\-geometry 80x40 \-\-command mutt \-\-tab \-\-command mc
.RS 4
Abre uma nova janela de terminal com uma geometria de 80 colunas, 40 linhas e 2 separadores, na qual a primeira executa o comando
\fBmutt\fR
e o segundo executa o comando
\fBmc\fR\&.
.RE
.SH "AMBIENTE"
.PP
xfce4\-terminal uses the Basedir Specification as defined on
\m[blue]\fBFreedesktop\&.org\fR\m[]\&\s-2\u[1]\d\s+2
to locate its data and configuration files\&. This means that file locations will be specified as a path relative to the directories described in the specification\&.
.PP
\fI${XDG_CONFIG_HOME}\fR
.RS 4
O primeiro diretório para procurar os ficheiros de configuração\&. Por omissão, está definido para
~/\&.config/\&.
.RE
.PP
\fI${XDG_CONFIG_DIRS}\fR
.RS 4
Uma lista separada por dois pontos de diretórios base contendo os dados da configuração\&. Por omissão, a aplicação irá procurar em
${sysconfdir}/xdg/\&. O valor de
\fI${sysconfdir}\fR
depende do modo como o programa foi compilado e costuma ser
/etc/
para pacotes binários\&.
.RE
.PP
\fI${XDG_DATA_HOME}\fR
.RS 4
A raiz de todo os ficheiros de dados específicos do utilizador\&. Por omissão, é
~/\&.local/share/\&.
.RE
.PP
\fI${XDG_DATA_DIRS}\fR
.RS 4
Uma lista de diretórios base ordenados de preferências onde os ficheiros de dados devem ser procurados em adição ao directório
\fI${XDG_DATA_HOME}\fR\&. Estes diretórios devem ser separados com dois pontos\&.
.RE
.SH "FICHEIROS"
.PP
${XDG_CONFIG_DIRS}/xfce4/terminal/terminalrc
.RS 4
Esta é a localização do ficheiro de configuração que inclui as preferências que controlam a aparência e comportamento do xfce4\-terminal\&.
.RE
.SH "VEJA TAMBéM"
.PP
\fBbash\fR(1),
\fBX\fR(7)
.SH "AUTHORS"
.PP
\fBNick Schermer\fR <\&nick@xfce\&.org\&>
.RS 4
Programador
.RE
.PP
\fBBenedikt Meurer\fR <\&benny@xfce\&.org\&>
.br
Programador de software, os\-cillation, Desenvolvimento do sistema, 
.RS 4
Programador
.RE
.SH "NOTES"
.IP " 1." 4
Freedesktop.org
.RS 4
\%http://freedesktop.org/
.RE
